Controllers/RoleController.cs
using SecurityFinal.Data;
using SecurityFinal.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityManager.Controllers {
    [Authorize(Roles = "ADMIN")]
    public class RoleController : Controller {

        private readonly AppDbContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public RoleController( AppDbContext db, RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager ) {
            _db = db;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() {

            var roles = _db.Roles.ToList();

            return View(roles);
        }

        [HttpGet]
        public IActionResult Upsert( string id ) {
            if (string.IsNullOrEmpty(id)) {
                return View();
            }
            else {
                var role = _db.Roles.FirstOrDefault(x => x.Id == id);
                return View(role);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert( IdentityRole model ) {
            if (await _roleManager.RoleExistsAsync(model.Name)) {
                // error
                TempData[SD.Error] = "Role Already Exists";
            }
            else {
                if (string.IsNullOrEmpty(model.Id)) {
                    // create
                    await _roleManager.CreateAsync(new IdentityRole { Name = model.Name });
                    TempData[SD.Success] = "Role Created Successfully";
                }
                else {
                    // update
                    var role = _db.Roles.FirstOrDefault(x => x.Id == model.Id);
                    if (role == null) {
                        TempData[SD.Error] = "Role Not Found";
                        return RedirectToAction(nameof(Index));

                    }
                    role.Name = model.Name;
                    role.NormalizedName = model.Name.ToUpper();
                    var result = await _roleManager.UpdateAsync(role);
                    TempData[SD.Success] = "Role Updated Successfully";
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete( string id ) {
            var role = _db.Roles.FirstOrDefault(y => y.Id == id);
            var userWithRole = _db.UserRoles.Where(u => u.RoleId == id).Count();
            if (userWithRole > 0) {
                TempData[SD.Error] = "Cannot delete role with active users assigned to it.";
                return RedirectToAction(nameof(Index));
            }
            if (role == null) {
                TempData[SD.Success] = "Role Note Found";
                return RedirectToAction(nameof(Index));
            }
            await _roleManager.DeleteAsync(role);
            TempData[SD.Success] = "Role Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SecurityFinal.Data;
using SecurityFinal.Models;
using SecurityFinal.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace SecurityFinal.Controllers {
    [Authorize(Roles = "ADMIN")]
    public class UserController : Controller {

        private readonly AppDbContext _db;
        public UserManager<IdentityUser> _userManager;
        public UserController( AppDbContext db, UserManager<IdentityUser> userManager ) {
            _db = db;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index() {
            var users = _db.AppUsers.ToList();
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in users) {
                var currentUserRole = userRoles.FirstOrDefault(x => x.UserId == user.Id);
                if (currentUserRole == null) {
                    user.Role = "None";
                    user.RoleId = "None";
                }
                else {
                    var r = roles.FirstOrDefault(role => role.Id == currentUserRole.RoleId);
                    user.Role = r.Name;
                    user.RoleId = r.Id;
                }
            }
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id) {
            if (string.IsNullOrEmpty(id)) {
                TempData[SD.Error] = "Invalid Id Format";
                return RedirectToAction(nameof(Index));
            }
            var user = await _db.AppUsers.FirstOrDefaultAsync(x => x.Id == id);
            if (user == null) {
                TempData[SD.Error] = "User not found";
                return RedirectToAction(nameof(Index));
            }
            var currentMovie = await _db.Movies.FirstOrDefaultAsync(x => x.Id == user.MovieId);
            var userMovies = await _db.UserMovies.Where(x => x.UserId == user.Id).ToListAsync();
            UserDetailViewModel userDetailViewModel = new UserDetailViewModel() {
                User = user,
                CurrentMovie = currentMovie != null ? currentMovie : new Movie(),
                PastMovies = userMovies != null ? userMovies : new List<UserMovie>(),
            };
            return View(userDetailViewModel);
        }

        [HttpGet]
        public IActionResult Edit( string id ) {
            var user = _db.AppUsers.FirstOrDefault(x => x.Id == id);
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            if (user == null) {
                TempData[SD.Error] = "User not found";
                return RedirectToAction(nameof(Index));
            }
            var currentUserRole = userRoles.FirstOrDefault(x => x.UserId == user.Id);
            if (currentUserRole != null) {
                var roleData = roles.FirstOrDefault(x => x.Id == currentUserRole.RoleId);
                user.Role = roleData.Name;
                user.RoleId = roleData.Id;
            }
            user.RoleList = roles.Select(x => new SelectListItem {
                Text = x.Name,
                Value = x.Id
            });
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit( AppUser model ) {
            if (ModelState.IsValid) {
                var user = _db.AppUsers.FirstOrDefault(x => x.Id == model.Id);
                var currentUserRole = _db.UserRoles.FirstOrDefault(x => x.UserId == user.Id);
                var roles = _db.Roles.ToList();
                if (user == null) {
                    TempData[SD.Error] = "User not found";
                    return RedirectToAction(nameof(Index));
                }
                if (currentUserRole != null) {
                    var existingRole = _db.Roles.Where(x => x.Id == currentUserRole.RoleId)
                        .Select(x => x.Name).FirstOrDefault(); // when you have users with single roles
                      //.Select(x => x.Name).ToList(); When you have users with multiple roles
                    // Remove old role
                    await _userManager.RemoveFromRoleAsync(user, existingRole);
                }
                // Add new role
                await _userManager.AddToRoleAsync(user, _db.Roles.FirstOrDefault(x => x.Id == model.RoleId).Name);
                user.Name = model.Name;

                _db.SaveChanges();
                TempData[SD.Success] = "User data updated successfully";
                return RedirectToAction(nameof(Index));
            }
            model.RoleList = _db.Roles.Select(x => new SelectListItem {
                Text = x.Name,
                Value = x.Id
            });
            return View(model);
        }

        [HttpPost]
        public IActionResult LockToggle( string id ) {
            var user = _db.AppUsers.FirstOrDefault(x => x.Id == id);
            if (user == null) {
                TempData[SD.Error] = "User not found";
                return RedirectToAction(nameof(Index));
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now) {
                // user is locked until atleast today and this will unlock them
                user.LockoutEnd = DateTime.Now;
                TempData[SD.Success] = "User Unlocked successfully";
            }
            else {
                // user is not locked so we lock till the specified time
                user.LockoutEnd = DateTime.Now.AddDays(5);
                TempData[SD.Success] = "User locked successfully";
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete( string id ) {
            var user = _db.AppUsers.FirstOrDefault(x => x.Id == id);
            if (user == null) {
                TempData[SD.Error] = "User not found";
                return RedirectToAction(nameof(Index));
            }
            _db.AppUsers.Remove(user);
            _db.SaveChanges();
            TempData[SD.Success] = "User Deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> um
@{
    IdentityUser user = await um.GetUserAsync(User);
    List<string> roles = new();
    if(user != null) {
        var roleList = await um.GetRolesAsync(user);
        roles = roleList.ToList();
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SecurityFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">SecurityFinal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        @if (User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="ListWatched">Past Movies</a>
                            </li>
                        }
                        @if ( roles != null && roles.Contains("ADMIN")) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SecurityFinal
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@using SecurityFinal.Utils

@if (TempData[SD.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[SD.Success]');
    </script>
}
@if (TempData[SD.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[SD.Error]');
    </script>
}